name: ql
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - matplotlib  # Add any other Conda packages here
  - pytest
  - pip:
      - aesthetic==0.6  # Add pip dependencies here if necessary
