name: ql
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - pytest
  - pip:
      - aesthetic==0.6  # Add pip dependencies here if necessary
      - loguru
      - importlib_resources>=5.0.0
