[build-system]
requires = [
    "setuptools>=61.0",
    "setuptools_scm",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0.0"
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"

[tool.setuptools.packages.find]
where = ["."]
include = ["quicklook*"]
exclude = ["static*", "notebook*", "tests*"]

[tool.setuptools.package-data]
"quicklook" = ["data/*.csv", "*.mplstyle"]
"quicklook.app" = ["templates/*.html"]

[tool.setuptools.exclude-package-data]
"quicklook.app" = ["static/outputs/*", "static/outputs/**/*"]

[project]
name = "quicklook-package"
dynamic = ["version"]
authors = [{name = "jpdeleon", email = "jpdeleon.bsap@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = [
    "setuptools",
    "matplotlib",
    "lightkurve>=2.5",
    "numpy>=2.0",
    "transitleastsquares>=1.32",
    "wotan>=1.10",
    "h5py>=3.10",
    "reproject>=0.13",
    "astroplan>=0.10",
    "loguru",
    "flask"
]

[project.optional-dependencies]
dev = [
    "pytest",           # run tests
    "pytest-benchmark", # measure performance
    "pytest-xdist",     # parallelize tests
    "mypy",             # static type checking
    "pre-commit",       # hook management
    "tox>=4.0",         # multi-env testing
    "ruff",             # linting and formatting
    #"flake8>=6.0"       # legacy linting
]

gui = ["flask", "flask-sock", "pytest-flask"]

notebooks = [
    "ipykernel",
    "jupyter",
    "nbconvert"
]

[project.urls]
Homepage = "https://github.com/jpdeleon/quicklook"

[tool.ruff]
line-length = 100

[tool.ruff.format]
# black formatted .py only (include = '\.pyi?$'); keep notebooks untouched.
exclude = ["*.ipynb"]

[tool.ruff.lint]
select = ["B", "C", "E", "F", "W", "B9"]
ignore = [
  "E203",
  "E266",
  "E501",
  "F403",
  "F401",
  "C901",
  "B904",  # exceptions
  "B006",  # Do not use mutable data structures for argument defaults
  "B008",  # Do not perform function call in argument defaults; in tglc.py
  "B028",  # No explicit `stacklevel` keyword argument found; in gls.py
  "B905",  # `zip()` without an explicit `strict=` parameter
  "C408",  # Unnecessary `dict()` call; in gls.py
]

[project.scripts]
ql = "quicklook.cli.ql:main"
read_tls = "quicklook.cli.read_tls:main"
rank_tls = "quicklook.cli.rank_tls:main"
ql-gui = "quicklook.app.app:main"
