#!/usr/bin/env python

import flammkuchen as fk
from glob import glob
import pandas as pd
from tqdm import tqdm
import argparse

parser = argparse.ArgumentParser(description="Summarize TLS results.")
parser.add_argument("indir", type=str)
args = parser.parse_args()

indir = args.indir
files = glob(indir + "/*.h5")
assert len(files) > 0, "no *.h5 files found!"

# print(files)
ss = []
errors = []
for file in tqdm(files):
    try:
        data = fk.load(file)
        d = {
            "TOI": data["toiid"],
            "TIC": data["ticid"],
            "power_gls": data["power_gls"][0],
            "SDE_tls": data["SDE"],
            "Porb_tls": data["period"],
            "Prot_gls": data["Prot_gls"][0],
            "Porb_tfop": data["period_tfop"][0],
            "depth": (1 - data["depth"]) * 1e3,
            "depth_tfop": data["depth_tfop"][0],
        }
        s = pd.Series(d)
        ss.append(s)
    except Exception as e:
        errors.append(data["toiid"])

# sort by sde
df = (
    pd.DataFrame(ss)
    .sort_values(
        by=["SDE_tls", "Prot_gls", "power_gls"], ascending=[False, True, False]
    )
    .reset_index(drop=True)
    .drop_duplicates()
)
fp = indir + "_tls.csv"
df.to_csv(fp)
print(f"Saved: {fp}")
print("Error:", errors)
