name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
        #python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        python-version: ["3.10"]
        tox-env: ["py310"]  # without dot

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,notebooks]"

      - name: Run tests and checks with tox
        run: |
          tox -e ${{ matrix.tox-env }}
          tox -e notebook
          tox -e lint
          tox -e format
          tox -e type
