name: Install and Test Package

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true

      - name: Install mamba
        run: conda install -n base -c conda-forge mamba

      - name: Cache Conda environment
        id: cache-conda
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs/ql
          key: ${{ runner.os }}-conda-${{ matrix.python-version }}-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-${{ matrix.python-version }}-

      - name: Remove existing Conda env if needed
        if: steps.cache-conda.outputs.cache-hit != 'true'
        run: conda env remove -n ql || echo "No existing env to remove"

      - name: Create environment
        if: steps.cache-conda.outputs.cache-hit != 'true'
        run: mamba env create -f environment.yml

      - name: Install pip dependencies
        shell: bash -l {0}
        run: |
          conda activate ql
          pip install -r requirements.txt

      - name: Install the package in editable mode
        shell: bash -l {0}
        run: |
          conda activate ql
          pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate ql
          pip install jupyter nbconvert
          echo "Running regular tests..."
          pytest -v -m "not notebook"
          echo "Running notebook tests..."
          pytest -v -m "notebook"

      - name: Build and Upload to PyPI
        if: github.event_name == 'release' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
        shell: bash -l {0}
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          conda activate ql
          pip install build twine
          python -m build
          twine upload dist/*
